version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    network_mode: host  # Container shares the host's network stack

  web:
    build: .
    container_name: iot_scanner_app
    volumes:
      - .:/app
    env_file:
      - .env
    network_mode: host  # Container shares the host's network stack
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - db
    network_mode: host  # Same network for pgadmin
    volumes:
      - ./servers.json:/pgadmin4/servers.json
