services:
  iot_device_1:
    image: alpine:latest
    volumes:
      - ./scripts:/scripts
    command: sh -c "apk add --no-cache wireless-tools dnsmasq iputils iw && chmod +x /scripts/connect_to_ap.sh && /scripts/connect_to_ap.sh"
    networks:
      iot_network:
    privileged: true
  iot_device_2:
    image: alpine:latest
    volumes:
      - ./scripts:/scripts
    command: sh -c "apk add --no-cache wireless-tools iputils dnsmasq iw && chmod +x /scripts/connect_to_ap.sh && /scripts/connect_to_ap.sh"
    networks:
      iot_network:
    privileged: true
networks:
  iot_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24